name: wishfly_shared
description: Wishfly shared code between client and server. This package should not be used directly.
version: 0.2.0
repository: https://github.com/Wishfly-dev/shared

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
